### ISSUE TITLE
Can't we just let it die in peace?

### ISSUE THREAD

**Issue by fcntl** [pakastin/open-source-flash#12]

**Comment by JasonIdris** [comment]
CODE SHOULD NEVER DIE. Flash was a great player. Let them open source it for everyone later. Do you really want to lose millions of games, animations, and more? Who knows? Somebody could even modify Flash and integrate it with HTML... or something. The point is... Heroes... I mean... Code never dies!

**Comment by DrivenByHim** [comment]
@JasonIdris I agree, Adobe should have Mercy on all the flash content creators of the world.

**Comment by rodorgas** [comment]
@JasonIdris Why do you think games and animations will be lost? Flash won't receive updates, but older versions will still be available. Browser can (and should) drop support, but you can run .swf without a browser…
Get over it guys.

**Comment by pakastin** [comment]
For now, but what about in the future? swf support is not baked in OS.

**Comment by RedRelay** [comment]
Why people could not use an old flash player version to play their favorite game ?

**Comment by albertdick** [comment]
> _Do you really want to lose millions of games, animations, and more?_

If that's your best argument for keeping the flash alive, then I'd rather it die.

**Comment by cprogrammer1994** [comment]
I grew up on miniclip games :)

**Comment by jens1o** [comment]
Me too @cprogrammer1994 🗡

**Comment by albertdick** [comment]
> I grew up on miniclip games :)

I grew up playing consoles and PC games that no longer exist, nor did I stop moving on because of that. When I miss them, I use emulators. It'll probably be the fate of the flash games.

Grow up guys.

**Comment by Silent-Hunter** [comment]
And the best way to make an 'emulator' for Flash is to have the source code! Seriously, what is the problem here? As long as it's just a standalone Flash player, I don't see the problem. Why don't you grow uo?
