### ISSUE TITLE
2030

### ISSUE THREAD

**Issue by est31** [pakastin/open-source-flash#13]
What about waiting with open sourcing flash until 2030?

Let me give a short explanation on why:

* I understand that flash has been used by creative people all over the world to create many beautiful (and many many more less beautiful :p) works. It would be a shame if those works became inaccessible for future generations.
* The same time, the widespread habit of forcing web surfers to install flash needs to die. Websites should be forced to get their stuff together and switch to HTML5. I won't expand further on why HTML5 should be chosen instead, you all know the points.
* Many website owners still deem it acceptable to require users to install flash, and by these websites stating that requirement, many users feel that they can't enjoy the web fully without flash player installed. Websites like scratch.mit.edu or crunchyroll or the HBO web player, similar for many local websites. As a German for example, the livestream of the news website tagesschau.de is still inaccessible for me without flash, even today. Similarly, the mindset "Flash is important in order to surf the web" is still in many people's heads. This makes them ask browser vendors for flash support, or just simply not use the browsers that have no flash support. This basically forms a vicious circle of users ready to install flash, and websites deeming it okay to require it.
* The vicious circle won't break from itself, or at least not fast enough. Sure, with time less and less websites will use and build on flash, but even today there are people who are convinced that everything is broken except flash, who put flash into new products and shrug off all of the issues flash has.

As a compromise to fix both cases, Adobe should wait with open sourcing flash until 2030. In that period, the number of users who have flash or are ready to install a browser with flash support if they reach a website with only flash support will hopefully reach the single percent range or even go below one percent. Currently, Flash is installed on [about 70%](https://hardware.metrics.mozilla.com/) of Firefox installs, many other browsers ship it by default, so its close to 100% for them. This will force website owners to come up with an alternative. As an example, it will force the scratch team to get their html5 player to a productive state, and will give very strong motivation for crunchyroll to push for its contracts to allow a HTML5 version of their website.

Why 2030? Popular (and flash was popular) technologies have a long tail, even when the company that invented it abandons them. Windows XP still has a market share of about 7%, 3 years after its official deprecation, and I think we'll need to wait a long time as well to get rid of all flash content on the web. Its also likely already that for years following the 2020 abandon, many people will keep an outdated browser around which still supports flash, and its likely that flash will remain downloadable from shady websites.

Also, the future is patient :) nobody cares in 2050 if there was a 10 year period where flash was usable only if you have broken the law or have kept some archived install around, but they will curse us if flash still remains required for some websites :).

**Comment by JasonIdris** [comment]
I honestly don't care that much about flash as a service. It needs to die.... AS A SERVICE. As a service it is a crappy thing that I don't understand why Adobe still supports. But it's not about the service. It is about what depends on it. Millions of Flash apps will have the rug pulled from under them. "But why don't they just convert to HTML5," Adobe says. "It's easy" companies say. IT IS NOT THAT SIMPLE. ASK ANY FLASH DEV. Go ahead and kill Flash. But leave us with the code or at least a conversion tool.

**Comment by pakastin** [comment]
I changed "Flash player" –> "Flash" in README. The spec itself should be open sourced. Flash player should die as is, that's for sure.
