### ISSUE TITLE
Another language

### ISSUE THREAD

**Issue by ghost** [pakastin/open-source-flash#132]
I've had some issues with existing languages, so I believe a new ActionScript dialect should not be an issue. Look here: [developer-guide](https://github.com/shockscript/shockscript-developer-guide/blob/master/characteristics.md#shockscript-characteristics) There's a parser/verifier, almost a compiler.

**Comment by Hydroper** [comment]
The compiler is implemented in Node.js and it does resolves symbols. However, no codegen. I'd like to know if anyone is interested in working in codegen, using the existing semantic data model in this [compiler project](https://github.com/shockscript/sxc/tree/master/src).

**Comment by Hydroper** [comment]
OK, I think I should continue on codegen again, since I've not completed a specification yet.........
