### ISSUE TITLE
About the Chinese version of Flash and more

### ISSUE THREAD

**Issue by ZeroAurora** [pakastin/open-source-flash#134]
It is widely known that Adobe sold the permission of redistributing Flash in China to Chong Cheng Inc. (a.k.a 2144)[[1]], and this action has been proven wrong. According to many users in China, the Chinese-flavored Adobe Flash is just like a "malware", running a "helper service", displaying ads and spying on users' privacy.[[2]]
I would like to attach a request to your letter: If Adobe open-sourced Flash, they should also revoke the partenership with Chong Cheng, and provide a clean binary installer without the so-called "helper service" if possible.
Also, I would like to contribute Chinese translation if time permits! (though I don't have much time, eh)

[1]: https://helpx.adobe.com/flash-player/kb/how-to-dowload-flash-player-in-china.html
[2]: https://community.adobe.com/t5/flash-player/adobe-s-partner-2144-in-china-has-suspicious-malware-actions-in-flash-player-distribution/td-p/9967577

---
Update:
I read README again and found that you said that `We're not saying Flash and Shockwave player should be preserved as is`. Well that's OK. If you think this issue is out-of-topic please close it. I'm sorry for bothering.

**Comment by Brian151** [comment]
there's a very good chance part of that issue is with the chinese government, themselves. they don't exactly discourage spyware, they practically mandate/encourage it... at least, that's how i understand things...

**Comment by ZeroAurora** [comment]
Adobe is claiming that the life of Flash will continue, only in China. Bad news.

**Comment by PippoApps** [comment]
> Adobe is claiming that the life of Flash will continue, only in China. Bad news.

Where is the source of this? I couldn't find anything related.

**Comment by Cleod9** [comment]
> Where is the source of this? I couldn't find anything related.


I couldn't find much but when I looked into it I found this recent article:
https://www.smalltechnews.com/archives/164798

It's not exactly clear what the deal is since not many people are talking about it, but I guess this "special" version of the Flash Player may continue indefinitely in China.

**Comment by ZeroAurora** [comment]
https://www.ithome.com/0/493/681.htm
It's a Chinese website, so you may want to use a translator.
