### ISSUE TITLE
So long as authority inspires awe, confusion and absurdity enhance conservative tendencies in society.

### ISSUE THREAD

**Issue by Izhaki** [pakastin/open-source-flash#15]
> So long as authority inspires awe, confusion and absurdity enhance conservative tendencies in society. Firstly, because clear and logical thinking leads to a cumulation of knowledge (of which the progress of the natural sciences provides the best example) and the advance of knowledge sooner or later undermines the traditional order. Confused thinking, on the other hand, leads nowhere in particular and can be indulged indefinitely without producing any impact upon the world.

 -- Stanislav Andreski, Social Sciences as Sorcery (1972, p. 90)

**Comment by pakastin** [comment]
Sorry but what's the issue here?

**Comment by GeorgeWL** [comment]
@pakastin think he must have been high. Only logical explanation.

His other issues are perfectly normal and make sense.

Just close it.
