### ISSUE TITLE
Has there been any work towards a Flash to HTML5 converter instead?

### ISSUE THREAD

**Issue by GeorgeWL** [pakastin/open-source-flash#23]

**Comment by pakastin** [comment]
Yeah, they're listed in README:
https://github.com/pakastin/open-source-flash#current-state-of-flash-preservation

**Comment by Uzume** [comment]
I notice the quoted section does not currently mention [CreateJS](http://createjs.com/) ( [@Wikipedia](https://en.wikipedia.org/wiki/CreateJS) ) which Adobe adopted as a replacement for [Wallaby](https://en.wikipedia.org/wiki/Adobe_Wallaby). [CreateJS@GitHub](https://github.com/CreateJS) is available in several repos under MIT License
