### ISSUE TITLE
Explain why preserving history is fundamental for humans

### ISSUE THREAD

**Issue by dcaravana** [pakastin/open-source-flash#25]
Put somewhere a clear statement explaining that  _"those who do not learn history are doomed to repeat it"_.

In this case it's an obvious reference to why Flash has been rejected at some point and now it's being killed officially.

Why, after a very long and successful history, this piece of tech has been rejected and then killed?

Is it related to business strategy only (i.e. Apple vs the world) or are there tech reasons?

All this should be explored in deep and it will be quite difficult to do if there will be no access to the actual tech.

**Comment by ancarda** [comment]
Why aren't the various open source Flash players or virtual machines good enough for preserving history? Even years after 2020, I suspect Flash Player would run fine given Microsoft's good backwards compatibility. People often use old software and play old games in emulators or virtual machines - this is the first I've seen someone fight companies to open source the software.

Example: There's no source code for old Legend of Zelda games but there are virtual consoles on DS and Wii. I play old SNES and N64 games every day on my laptop with OpenEmu and on my DS.

>Why, after a very long and successful history, this piece of tech has been rejected and then killed?

Why do we specifically need Adobe Flash Player to be open source? I don't understand how having access to the source code helps us answer this question.

At best, it would be interesting to see how Flash Player was built, but patent concerns (see #9) mean that Adobe might need a very good reason to open source Flash Player. Curiosity may not be enough.

**Comment by dcaravana** [comment]
You may not be familiar with software development, this is why you probably don't understand why.

I mean, as a gamer you may be interested in Zelda binaries only, but as a game developer you would probably love to understand how those old binaries where build, what was the software architecture behind, the design decisions, the tricks, the workarounds, etc.

Also take into account that having the source code is not mandatory because you can always reverse engineer the binary, so you can have access to the inner workings, but all the reasons behind them can only be inferred or just guessed as they will be lost forever.

Moreover, if Adobe would be so kind to release also the full SCM repository, that could easily became a treasure trove for software engineers that want to understand how a huge (and old) product evolved through the years.

There are a lot of good reasons behind open sourcing this kind of product, but they come with a lot of work attached so they may not be immediately evident to everyone.

**Comment by ancarda** [comment]
Those answers all seem to come under curiosity though - how does access to the code help us understand why Flash was discontinued?

I only gave Zelda as an example because I don't use a lot of old software. Maybe something like WordStar as a better example? I can't think of good examples in software which is why I went with a game instead.

**Comment by dcaravana** [comment]
No one can reply to your question until the code is examined - see the problem?

Do you really think that all this may just be framed from a curiosity standpoint?

All the knowledge (not only related to tech) that drives human civilisation today is the result of some form of study, summarisation and transmission to the new generations, there are millions of people out there working hard as historians, researchers, teachers, lecturers, students, etc to make sure you and me get the best solutions to basically any problem.

Do you really think that the experience of building Zelda or WordStar has not been important to the evolution of software development? I'm sure the people behind them moved to something else brining with them important learned lessons.

Personally, I've learned the basics of programming on a Commodore VIC-20 around 1984 (interesting year BTW) because I was forced to manually type BASIC V2 source of games published on [paper] magazines, since I didn't own a mass storage device at the time!

After a few years, I've learned the inner workings of computers as I started reverse-engineer the OS in ROM of a Commodore PLUS/4, and again I was using a [paper] notepad to write the assembler instructions down!

So yes, in line of principle, I'm totally convinced that open sourcing Flash and any other discontinued big products should be mandatory.

My advice is you watch this video by Uncle Bob Martin (quite famous), it's long but it's absolutely worth it and very much better in explaining why history is important and why it's important to preserve and know it: https://youtu.be/ecIWPzGEbFc

**Comment by ancarda** [comment]
Thank you for the link, I'll watch it.

**Comment by pakastin** [comment]
Good points!
