### ISSUE TITLE
Is there any way to set up a socket connection in HTML without flash?

### ISSUE THREAD

**Issue by zongwan** [pakastin/open-source-flash#27]
I feel so disappoint.

A lot of intelligent devices use the TCP/UDP port.

### Solution
- [ ] the intelligent device supports Web socket
- [ ] next generation interface or protocol in Web ? HTTP 2 ? MQTT ? WebRTC ?
- [ ] next generation network technology ? Wi-Fi 2 ? Li-Fi ? Lightbridge ?
- [ ] web extension
- [ ] ~~the next generation intelligent device makes lots of money and kills the Web browser by providing new communication way.~~

Could someone give me more informations ?

**Comment by ancarda** [comment]
There's some early work here https://www.w3.org/TR/tcp-udp-sockets/ but it'll be some time until it's implemented in browsers, if at all. This isn't on caniuse.com yet but there's an open PR for it here: https://github.com/Fyrd/caniuse/issues/3622

**Comment by pakastin** [comment]
[socket.io](https://socket.io) is an alternative for HTML5..

**Comment by pakastin** [comment]
..not exactly the same though

**Comment by demurgos** [comment]
If you want an UDP channel, you need to hack something on top of WebRTC at the moment.
