### ISSUE TITLE
Haxe Swf abilities/links

### ISSUE THREAD

**Issue by Justinfront** [pakastin/open-source-flash#29]
Haxe has resources for Swf, and compiles to ABC and swf
For general reading and writing format library has some powers not so much over graphics.
https://github.com/HaxeFoundation/format/tree/master/format/swf
OpenFL can read and play swf's but not old ones.
https://lib.haxe.org/p/swf
NME similar ( same? )
https://github.com/nmehost/gm2d/tree/master/gm2d/swf
HxSwfml there are some github sources but it's not clear which is best but original here:
https://code.google.com/archive/p/hxswfml/
Theoretically OpenFL/NME could be used as a base for a new SWF player.

**Comment by pakastin** [comment]
Added some Haxe stuff to README. If you have something to add, please open a pull request – thanks!
