### ISSUE TITLE
Why not open-source the player?

### ISSUE THREAD

**Issue by akx** [pakastin/open-source-flash#32]
I think the [standalone player/debugger](http://www.adobe.com/support/flashplayer/debug_downloads.html) should definitely be in the scope of open-sourcing.

I understand and agree that keeping the web plugin alive is not the best of ideas.

**Comment by pakastin** [comment]
True

**Comment by yosun** [comment]
there are several opensource flash players out there already

**Comment by pakastin** [comment]
Although they are not complete..

**Comment by pakastin** [comment]
Everything is open, open source Flash player is one of the possibilities. Closing this issue because there's conversation going on elsewhere.
