### ISSUE TITLE
Flash spec is already open source right? 

### ISSUE THREAD

**Issue by yosun** [pakastin/open-source-flash#36]
I contributed to a few sourceforge Flash opensource projects in 2000... I believe the spec is already open source. I appreciate the community activism in remembering Flash, but also, Adobe (Macromedia) has already done so?

**Comment by pakastin** [comment]
I honestly don't know for sure, but I think the player is only partly open source.

**Comment by Minoru** [comment]
Wikipedia [claims](https://en.wikipedia.org/wiki/Adobe_Flash#Specifications) that *some* specs are open, but they don't cover all the relevant technologies.

**Comment by pakastin** [comment]
Duplicate to #54, closing

**Comment by jgranick** [comment]
The SWF specification is open, but that is very different from having an implementation capable of running it :smile:
