### ISSUE TITLE
Flashmixer

### ISSUE THREAD

**Issue by klappacher** [pakastin/open-source-flash#38]
Stumbled upon this petition because The Next Web wrote an article about it:
https://thenextweb.com/dd/2017/07/28/instead-of-killing-flash-we-should-save-it-for-posterity/

One piece of Flash-software I would like to be preserved is **Flashmixer**. It's the first vj-software I've used. I guess the project startet around 2000 and it was a really cool and advanced app back then.

For some reason the website is still alive: http://www.flashmixer.de
Here's a screenshot: http://www.audiovisualizers.com/toolshak/vjprgpix/flashmixer/flashmixer.htm

In addition here's an old article (2002) from the German De:Bug magazine when Flash was really popular among vjs: http://de-bug.de/mag/vj-flashmixer/

**Comment by pakastin** [comment]
Added, thanks!
