### ISSUE TITLE
what about reverse enginering tools (from swf to fla)

### ISSUE THREAD

**Issue by Elmapul** [pakastin/open-source-flash#39]
i foind an tool that is able to convert compiled flash files (swf) back to project files (fla)
AFAIK adobe animate can open .fla files and export it as HTML5.
this may be usefull in preserving content.
i think you should quote it here:
" Current state of Flash preservation"
but i'm not sure about the legal constraints of tools like that.

another sugestion: 
maybe we should create an script (eg: grease monkey script or browser add'on) that look for the checksum of an swf and search for its html5 conversion (if someone already uploaded it somewhere) to provide it where the original content would be present, or ask the user to use the afore mentioned tool  to revert it to fla file, then use an tool like adobe animate to export to html5 (i couldnt find open source adobe animate alternatives, compatible with its file format) and upload to an database where it will be tracked back the next time someone open this file.

**Comment by pakastin** [comment]
Could you make a PR for README?

**Comment by Elmapul** [comment]
PR?

**Comment by pakastin** [comment]
Pull request..

**Comment by pakastin** [comment]
I think some things have added to README already, so closing.. If you have something to add, please open a pull request – thanks!
