### ISSUE TITLE
Adobe Air

### ISSUE THREAD

**Issue by HendrixString** [pakastin/open-source-flash#50]
Also add Adobe AIR. one of the iconic runtimes.
heavily used by:  
* [https://gamua.com/starling/](https://gamua.com/starling/)
* [https://feathersui.com/](https://feathersui.com/)
  
Adobe also released the source for `flask` and together with the AIR
runtime, the developers would be able to still publish updated SDKs

**Comment by pakastin** [comment]
Could you make a pull request, thanks!
