### ISSUE TITLE
AS2,AS3, a must for millions of developers around the world

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [pakastin/open-source-flash#51]
It's time to hijack those bastards, license or not, they will go to hell to cut the grass under years of hard development. They don't want people to use internet with advanced technologies, they want the corporations only profit from their own html5 javascript crap standards.
We, people, are going to show how ridiculous they are to try (another time) to control us.
let's decompile AS2 and AS3, and let's do better than Html5 and javascript, even compatible with old browsers which is still widely used for long time around the world.

**Comment by Zegnat** [comment]
Maybe I am confused, but there is [a full definition of AS3](http://help.adobe.com/livedocs/specs/actionscript/3/wwhelp/wwhimpl/js/html/wwhelp.htm) available from Adobe already. It is a superset of ECMAScript (that same very publicly documented scripting language as JavaScript “crap” is built on). There is no controlling super power here. Feel free to keep using AS3 with any interpreter that accepts it (Haxe?) or write your own interpreter.

What exactly is it you are asking for here?

**Comment by zwetan** [comment]
It is indeed a bit confusing

for info a copy of the whole AS3 spec is available here
https://github.com/as3lang/ActionScript3/wiki/Specification

You can use AS3 with an open source runtime
see project [Redtamarin](https://github.com/Corsaair/redtamarin)

The Redtamarin runtime (eg. **redshell** ) can run
`*.as` files (not compiled), `*.abc` files (actionscript bytecode),
or `*.swf` files, see [Running Programs](https://github.com/Corsaair/redtamarin/wiki/RunningPrograms).

I don't think Haxe "as is" can run AS3, you will need to convert it first to the haxe language,
see [Using AS3 classes in Haxe](http://old.haxe.org/doc/flash/usingas3classes)
and [as3hx](https://github.com/HaxeFoundation/as3hx) project.

There are some limitations, eg. `delete` keyword, etc.

**Comment by pakastin** [comment]
See #54, especially [this comment](https://github.com/pakastin/open-source-flash/issues/54#issuecomment-319695905). Only the Flash core is open sourced, but there's many things missing.
