### ISSUE TITLE
Use petition repo to pool info on state of flash preservation?

### ISSUE THREAD

**Issue by jcahill** [pakastin/open-source-flash#6]
We're already here. This might be the best place for collective tl;dr of what exists, how behaviors differ, support matrix etc.

e.g.

- [Gnash](https://www.gnu.org/software/gnash/)
- [Lightspark](https://lightspark.github.io/)
- [Shumway](https://mozilla.github.io/shumway/)

**Comment by pakastin** [comment]
I add those to README, thanks!
