### ISSUE TITLE
bad info

### ISSUE THREAD

**Issue by devlfm** [pakastin/open-source-flash#60]
Hi,

please change this: FLEX - the main display list / layout engine made by Adobe configured with MXML, was open sourced by Adobe. Now it is being developed by the guys at NextGen ActionScript

to: 

FLEX - the main display list / layout engine made by Adobe configured with MXML, was open sourced by Adobe. Now it is being developed by the guys at Apache Flex http://flex.apache.org/index.html

**Comment by pakastin** [comment]
Ping @HendrixString (#53) 🙂

**Comment by joshtynjala** [comment]
#61

**Comment by madovsky** [comment]
404 :(

**Comment by pakastin** [comment]
http://flex.apache.org/index.html
