### ISSUE TITLE
my projects of this type

### ISSUE THREAD

**Issue by Brian151** [pakastin/open-source-flash#62]
https://github.com/Brian151/OpenShockwave/
(name soon to change)
goals:
decompilation of all shockwave media types, including W3D models
editing of shockwave movies and casts

https://github.com/Brian151/Various-Projects/tree/master/Flash/fla_buster
goals: 
document XFL format
convert XFL to other formats
possibly bust 'binary blob' FLA
convert to HTML5 in a 'better' way
(currently un-named as it's currently a personal project with only me contributing)

**Comment by asdfjk1** [comment]
This is very cool, how far have you gotten with this? I'm not sure if you're familiar with these other projects, but they may come of handy if you're not.
https://github.com/eriksoe/Schockabsorber
https://gist.github.com/TheCjw/b21d82dfe43107c58a6f
They have some nice information on the file format.

**Comment by pakastin** [comment]
Feel free to create a pull request if you want to add these to README or fix/add anything.. 😉

**Comment by Brian151** [comment]
Well, from where I started? very...

some of my own shockwave information comes from shockabsorber
Yes, i read the memory disclosure thing. Not sure of what value it is to me, though...

I'll consider a PR in the future
Currently just getting back to working on shockwave, took a hiatus for LD39

**Comment by asdfjk1** [comment]
Well, keep us updated as you work on openshockwave and all the remakes of all the lego shockwave games.

**Comment by Brian151** [comment]
umm, sure...
and i only presently plan to re-make spybotics, and POSSIBLY world builder. the others involve stuff i ain't comfortable dabbling around with yet. i also have way bigger projects i'd like to work on as-is...

and... Hopefully soon, "OpenShockwave" will officially be known as Earthquake

**Comment by madovsky** [comment]
shockweb ;)

**Comment by Brian151** [comment]
There's a reasoning for our naming conventions, though...

on PR's:
I've never really done one of these, and I also am afraid of totally screwing-up the readme.md as I don't exactly understand the syntax. I just use plaintext files... lol

**Comment by pakastin** [comment]
Here's an easy tutorial: https://guides.github.com/features/mastering-markdown/ 😉

**Comment by Brian151** [comment]
re-opening at least temporarily, because as of about an hour ago:
https://github.com/Earthquake-Project
