### ISSUE TITLE
What will happen if flash become better than HTML5?

### ISSUE THREAD

**Issue by FreedomXingyuLu** [pakastin/open-source-flash#66]

**Comment by pakastin** [comment]
Sorry, but quite unrelated to the project.

**Comment by madovsky** [comment]
well, we can answer easily, after thousands of test between both
Flash is much more fluid and fast than html5, also multi thread which javascript html5 is not.
I don't talk about major functions that does not exist in javascript and vector management much more advanced in actionscript

**Comment by madovsky** [comment]
I think let people choose the technology they like to develop the net is
much more democratic rather than to impose one tech for everybody which is obviously
a communist like internet development

**Comment by pakastin** [comment]
btw. check out [RE:DOM](https://redom.js.org) JS library – it's super fast and easy to use (no virtualdom, but still [among the fastest libraries out there](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html)).

**Comment by madovsky** [comment]
pakastin: I hate javascript, I lost days and month to make it compatible with all browsers and version during my last 20 years of development, I'm traumatised now when I should develop in JS :)

**Comment by pakastin** [comment]
Ahhah, luckily it's slightly better nowadays with the evergreen browsers..

**Comment by madovsky** [comment]
sure, but think about millions of computers with an old system, and companies that don't want to change anything in their computer system because of money or else.
evergreeen browsers are the same. Today I'm facing the same compatibility problems with for example Edge, Chrome and Firefox

**Comment by pakastin** [comment]
RE:DOM should work in [IE6 and up](https://redom.js.org/documentation/#browser-support).. But yeah, there's always some small things to notice.

**Comment by GitFred14** [comment]
How do you DISABLE the emails that pour out from this?

I am highly interested in the Flash player open source version
(still having several flash sites of my own)
but I certainly don't need an email 
for each 
 * little troll battle shot (someone is not bright enough to ignore them)
 * each checkin
 * blah, blah chat between a user or two.

I have unsubscribed via the email link 4 times and also on the web directly -- but the emails still come.

**Comment by pakastin** [comment]
On the right hand side there's "unsubscribe" button..

**Comment by pakastin** [comment]
oh, and there's also "unwatch" button on top

**Comment by GitFred14** [comment]
Thanks -- I actually did the unsubscribe button -- and it did not work.

I'll try the unwatch now.

Toi be honest -- I would prefer to get the emails, 
as I am as stuck as many are with tremendous effort on flash sites now getting screwed;
but there is just way too much 
Non-Flash-Open-Source content.

Thanks

**Comment by pakastin** [comment]
Tell me about it 😄
