### ISSUE TITLE
About the code of conduct, issues, discussions and such.

### ISSUE THREAD

**Issue by ImJustTatan** [pakastin/open-source-flash#68]
I love Flash, AS and Shockwave (just as many of the signers here), and I really want it to get open-sourced. I really do understand that there is people who doesn't want it to be alive in our web browsers (mainly due to security flaws), and it's alright if you even post an issue about it. But please, PLEASE don't insult anyone because of it. Same for Flash defenders. Respect, to be respected.

This is something that has been bothering me since I started watching this git, since I do receive emails and notifications about it. I'm talking about discussions and conversations where the only thing that's present is insulting, fighting and calling out the code of conduct every three replies. This is a problem. There is one user (whose name won't be mentioned, but anyone who has been active here knows who he is and he's probably going to reply this anyways) that has been defending AS and Flash. That's fine. But calling those against the cause "trolls", "zombies full with stupidity" and "control minded people" is going a little _too_ far. I get that you had really bad experience with JavaScript, but there is people who loves it (I like it just as much as I like Flash and AS), and you can't attack them for that. Not liking Flash is not a form of trolling, nor is opposing this git.

The only reason for this issue to be written is because of how I really, really want to be part of the discussion, but I'm afraid it's gonna end in a stupidly useless fight like other issues did (and still do). I constantly receive emails about people fighting against other people in this git just to defend (or attack) Flash, which is a shame, because this petition is something I want to calmly talk about, without getting insulted because of me thinking that Flash getting featured in web browsers is bad _(ahem)_.

Please, people, don't insult just to defend your stand. We all have different perspectives, let's just share them without being called a "control minded stupid zombie". I am really tired of how the issues are managing the opinions, and I've seen some really interesting points of view that got trashed away because of the opposing insults.

Respect others' points of view, just as much as you defend yours. And please read the [code of conduct](https://github.com/pakastin/open-source-flash/blob/master/CODE_OF_CONDUCT.md) to see more about how to face other opinions.

**Comment by asdfjk1** [comment]
The code of conduct honestly should be removed, it's completely unnecessary. If someone is clearly trolling, how about you stop giving them attention because that's what they crave.

**Comment by ImJustTatan** [comment]
> If someone is clearly trolling, how about you stop giving them attention because that's what they crave.

Yeah, I see what you mean. The problem is that the half(?)-mentioned user is posting on every issue, and everyone is giving him attention (if he's actually trolling). I've been waiting for someone to do something, but the problem just repeated, and repeated, and repeated... I don't know, maybe I'm wrong and I shouldn't give it such importance?

**Comment by pakastin** [comment]
Yeah, the best action is to ignore. People have mixed feelings about Flash and JavaScript (both deeply loved or strongly hated). I hope we could keep the conversation here respectable.

My problem with trolling is that I'm not native English speaker so I might sound rude even if I don't mean. That's why I keep low profile as well.

**Comment by madovsky** [comment]
ImJustTatan: We have another proof of a technology conspiracy with all what's happening on this repository.
this kind of behavior from some suspicious people shows clearly there is some strong motivation to continue to ban flash and bring as an excuse security holes that happened 10 years ago.
Also something not really natural about this story, absolutely no one criticized javascript, which is also full of imperfections, but no one talk about it. Anyhow, it smells really like a psyop from brotherhood.

**Comment by My1** [comment]
"absolutely no one criticized javascript"

well I didnt do it here yet but JS is similarly annoying as flash and honestly sites that wont work without JS are (with the exception of big applications like word online, which I dont use anyway) in my opinion not good websites.

especially on bad connections I dont need flash, JS, Java or anything on that side to make the site more "active".


also we are not (just) talking about holes from many years ago. just this year alone, flash had 55 Code execution vulnerabilites, and in total. about 80% of flash's holes are code execution [(Source)](https://www.cvedetails.com/product/15031/Google-Chrome.html?vendor_id=1224), which (as far as I understand) is aside from privilege gaining, one of the worst vulnerability types.

**Comment by pakastin** [comment]
I think everyone agrees about code of conduct. Let's keep the talk nice and on topic. I will close the issue now.
