### ISSUE TITLE
Art project: Labuat - Soy tu Aire

### ISSUE THREAD

**Issue by ei-grad** [pakastin/open-source-flash#70]
The cite from the [developers site](www.badabing.es/v4/portfolio/labuat/) about the project:

> Our most famous project for the singer Labuat was a creative idea by spanish agency Herraiz & Soto. The project tried to replicate the experience of painitng with ink in the air following the rhythm of a song. Those manning the mouse can drive the graphics, swirling at will. Try it out and then hit Replay for a mesmerizing Web experience, or hit Record and send your motion painting to a friend.
> 
> The song was the first single of the new record by Labuat. The experience proved to be as delicate and beautiful as the melody, and won several prizes around the world, including a Lion at Cannes, FWA of the year by popular election and many national prizes. It was also included by the influential Time magazine in their list of best websites of 2010.
> 
> There was a projection of the site mapped into a building where users could control it with a Wii controller.

This one absolutely must be in the art projects list, but its original site http://soytuaire.labuat.com/ is gone :-(.

**Comment by ei-grad** [comment]
There was a http://soytuaire.labuat.com/labuat.swf, but I don't see its copy anywhere now. Google doesn't help and webarchive only has an html page, .swf file is missing :-(.

**Comment by ei-grad** [comment]
There are some youtube videos to see how it looked like - https://www.youtube.com/results?search_query=labuat+soy+tu+aire

**Comment by ei-grad** [comment]
Found it with Yandex on 4pda.ru :-) [labuat.zip](https://github.com/pakastin/open-source-flash/files/1202281/labuat.zip)

I think we should host it somewhere on github pages, for example. But there is copyright question. Credits says that it is developed by http://herraizsoto.com/, http://www.zumbakamera.com/ and http://www.badabing.es/v4/. Not sure about music.

**Comment by pakastin** [comment]
Please feel free to make a pull request to README 😉

**Comment by herraizsoto** [comment]
@ei-grad 👋  we're glad you want to feature this project. We actually made a backup and we host it [here](http://stuff.herraizsoto.com/works/2009/labuat/soytuaire/).

**Comment by ROBERT-MCDOWELL** [comment]
very nice concept, thanks

**Comment by Brian151** [comment]
That is AWESOME!

**Comment by Cleod9** [comment]
Holy smokes that was gorgeous!!

**Comment by Kolineal** [comment]
@herraizsoto it's gone again ;( is there an updated link?

**Comment by herraizsoto** [comment]
@Kolineal Hey, we had a SSL certificate renewal that didn't work as expected. Everything is up again, also we disabled the 2009 "no flash" redirect since it failed to detect newer versions of flash.

Thank you for telling us!

**Comment by zeogox** [comment]
it's gone again :(

**Comment by herraizsoto** [comment]
> it's gone again :(

Thanks for your report. It should be up again.

**Comment by sachgu** [comment]
I was looking for it today, but it seems that it's not hosted by Adobe Flash Player anymore, is there anything that can be done?

**Comment by BuchyOne** [comment]
Not the same, I know, but at least the genius of the animation can be viewed as a video on the Herraiz Soto site: 

[https://herraizsoto.com/works/all/labuat/](url)
