### ISSUE TITLE
Adobe, we are ok to convert our As2/As3 to what you want, but....

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [pakastin/open-source-flash#77]
- Why don't you provide any software helping your customers to convert it with
all full function compatible?
- If not, who will pay all the companies, self employed and hobbyist who are dependent of flash player to reprogram everything (for the same result at the end) ?

thanks for your answer Mr Adobe

**Comment by zwetan** [comment]
your logic is ridiculously wrong.

let's say someone write a program in PHP
do you think it is legitimate to ask PHP to pay him/her to port his/her program to Python ?

off course not

same thing for Flash

when you built your programs in AS2/AS3 you did it for yourself not for Adobe,
Adobe does not owe you anything, you are free to port your programs to whatever you want

**Comment by fraang** [comment]
> If not, who will pay all the companies, self employed and hobbyist who are dependent of flash player to reprogram everything (for the same result at the end) ?
That's the reason why you should use open technology in the first place... if possible of course.

**Comment by pakastin** [comment]
Well, basically Adobe Animate already exports to HTML5 as well, but of course it's hard to be 1:1 with Flash and HTML5.
