### ISSUE TITLE
I don't love flash

### ISSUE THREAD

**Issue by lesmana** [pakastin/open-source-flash#78]
The current letter begins with: "We love Flash".

I don't love flash. I don't hate it either. I am signing this petition because I don't want a substantial part of internet history to be lost because of dead proprietary tchnology.

Please change the wording of the letter to be more neutral. As it is now I have trouble putting my name on a letter which implies that I love flash.

**Comment by pakastin** [comment]
Fair enough 🙂

**Comment by pokemonchw** [comment]
Yeah .I don't love flash too
but
It is a memory of the age
Who didn't use flash when he was young?
so.I am signing this
Although I'm not optimistic about it

**Comment by ROBERT-MCDOWELL** [comment]
we are not fan of flash too believe me, but when you start to use a language for years
it's fair enough to keep this language alive, especially when the performance are far better in certain cases.
also javascript stil not covers all the functions like multicast and multithread.
