### ISSUE TITLE
Won't happen

### ISSUE THREAD

**Issue by jrgp** [pakastin/open-source-flash#9]
I'm all for open sourcing flash as I don't think we should leave the existing thousands of flash games to rot (although they might work well enough under gnash), and I starred this repo.

However, I highly doubt Adobe will open source flash in its current state. Reasons:

- Adobe Flash is being migrated/integrated into a new product called Animate, which will retain the same .fla format

- Their flash player likely has tons of internal IP and uses proprietary libraries developed by other companies which were always intended to remain closed source

- At big companies, open sourcing big existing codebases isn't a simple matter of making a github repo and throwing code over the fence.

It would require lots of legal review and work to remove parts of the code which can't be open sourced due to agreement reasons.

This kind of corporate red tape would take months, and would adobe really want to put forth the engineering time and legal resources?

Typically when companies want to get involved in open source, they'll start an internal product with the initial intention of releasing it open source eventually and strategically use libraries which permit that. This isn't the case with this ~20 year old (think macromedia flash in the 90s and where it came from) codebase.

It would probably be better for the open source communities to focus on gnash (and other open source reverse engineered copies of flash player) development.

**Comment by abdulhannanali** [comment]
@jrgp Joe has given a very informed opinion and I agree with him. Let's focus on other open source alternatives if Adobe ends up rejecting this petition. Remember people Windows ME and Windows 98 are still not open sourced, even if it's not actively supported or being used by many people.

**Comment by pakastin** [comment]
Wouldn't be the first corporate thing open sourced for history reasons. Even Apple and Microsoft have open sourced many of their OS's source code.

**Comment by abdulhannanali** [comment]
@pakastin Any reference? Microsoft open sourced old OS code? Never heart

**Comment by pakastin** [comment]
@abdulhannanali For example MS-DOS and old Word: http://www.computerhistory.org/atchm/tag/microsoft/

Here's some of Apple's releases: http://www.computerhistory.org/atchm/tag/apple/
